export default interface Pokemon {
    "NUMBER": String,
    "CODE": String,
    "SERIAL": String,
    "NAME": String,
    "TYPE1": String,
    "TYPE2": String,
    "COLOR": String,
    "ABILITY1": String,
    "ABILITY2": String,
    "ABILITY HIDDEN": String,
    "GENERATION": String,
    "LEGENDARY": String,
    "MEGA_EVOLUTION": String,
    "HEIGHT": String,
    "WEIGHT": String,
    "HP": String,
    "ATK": String,
    "DEF": String,
    "SP_ATK": String,
    "SP_DEF": String,
    "SPD": String,
    "TOTAL": String
}